### ISSUE TITLE
когда секас

### ISSUE THREAD

**Issue by ilka77297592739385** [shark01d/hex-brawl-v25#1]

**Comment by bQnQn** [comment]
когда рак на горе свистнет

**Comment by shark01d** [comment]
админ в чате, ебало офф

**Comment by ilka77297592739385** [comment]
Вы когда-нибудь видели член Gene? Я видел и сегодня я собираюсь специально утонуть в бассейне, чтобы он меня спас, а потом я бы начал флиртовать с ним, он покраснеет и я вытащу его член из шорт. Он смутится, но меня это заводит. Я возьму его член в ротик и начну облизывать и потихоньку задвигать дальше, а затем медленно сосать, пока он не заполнит мой рот великолепной спермой. Дальше я сниму свои джинсы и сяду на его член. Я буду быстро прыгать, а он мне дрочить, а затем, когда весь пол покроется одним слоем спермы, я немного передохну и буду ему дрочить и брать в рот, а затем начну прыгать еще быстрее. Потом, когда уже стемнеет и мы все в конче, он посадит меня на мотоцикл и меня будет трясти на его хуе. Пару раз кончив, он довезет меня домой и мы будем переписываться, представляя как мы все это повторяем. 
Главное - не обложаться завтра, а дальше он мой

**Comment by shark01d** [comment]
сосать
