### ISSUE TITLE
дурачёк

### ISSUE THREAD

**Issue by iamnalinor** [shark01d/hex-brawl-v25#3]
не py main.py, а python3 main.py

**Comment by TheAcelot** [comment]
Он говорил что у него только на py запускает, если ввести python3/python то просто выведет в консоль "Python"

**Comment by iamnalinor** [comment]
спермукс момент

или виндоус момент, но у меня на винде все зашибись

**Comment by TheAcelot** [comment]
Он ток с винды запускает

**Comment by shark01d** [comment]
> не py main.py, а python3 main.py

я поставил питонизатор 3.10 и там такие
